### ISSUE TITLE
ITEM "PROBLEMA"

### ISSUE THREAD

**Issue by Camila-R** [Camila-R/hackerrank-testes#2]
## O QUE?
Desenvolver um item chamado "PROBLEMA" para que o entregador possa reportar alguma situação.
____
## POR QUÊ?
- Com o aumento da demanda, entre uma entrega e outra pode acontecer um imprevisto com o entregador e, por meio desse novo item no app, o entregador pode reportar a situação e a DM possa selecionar um novo entregador para a demanda.

- Existe a possibilidade de o entregador aguardar por muito tempo o contato do cliente para finalizar uma entrega e isso pode prejudicar o tempo das demais entregas.
____
## O QUE FAZER?

Botões:

- [ ] Não conseguirei entregar no tempo (https://github.com/Camila-R/HackerRank_Algoritmos/issues/3).
- [ ] Não encontrei o endereço (https://github.com/Camila-R/HackerRank_Algoritmos/issues/4).
- [ ] Não encontrei alguém para receber (https://github.com/Camila-R/HackerRank_Algoritmos/issues/5).
- [ ] Não consegui entregar (https://github.com/Camila-R/HackerRank_Algoritmos/issues/6).
